migrate to copier template
Quantco/pre-commit-mirrors-clang-tidy pull request #23
Opened 2024-01-28 15:43 UTC by pavelzw

migrate to copier template

2024-01-28 18:41 UTC, 0xbe7a requested changes

2024-01-28 18:41 UTC, 0xbe7a commented on .github/workflows/tag.yml
> +          version-extraction-override: 'regex:\s+- clang-tidy=(\d+.\d+.\d+)'
This needs to match the conda package name, right?

2024-01-31 18:50 UTC, pavelzw commented on .copier-answers.yml
> +description: This hook runs clang-tidy.
```suggestion
conda_package: clangdev
description: This hook runs clang-tidy.
```

2024-01-31 21:17 UTC, 0xbe7a approved these changes

2024-01-31 21:17 UTC, merged